### PR TITLE
Audit final 2 - event emission

### PR DESCRIPTION
**Pull request by TJ-Everett**

### CODE REVIEW

**Review by oscarsernarosero — COMMENTED** [review]
We don't need an event when proposing new App Manager Address? I would say we do need an event there.

**Comment by TJ-Everett** [comment]
> We don't need an event when proposing new App Manager Address? I would say we do need an event there.

This is a good question and happy to drop an event in there if we need/want. gnosis safe UI has pending requests for their multi step approval process, would we want to mimic that? i.e. in our UI would we catch the event and then let the user know they have a pending proposed new address? @oscarsernarosero

**Comment by ShaneDuncan602** [comment]
> We don't need an event when proposing new App Manager Address? I would say we do need an event there.

Since we are already adding events to this, I agree. Good idea, Oscar.

**Comment by ShaneDuncan602** [comment]
Additionally, the ProtocolERC20 has the setAppManagerAddress function in it again. This function should be removed since the process goes through the propose/confirm functions in ProtocolTokenCommon. This was likely a merge issue.

**Review by ShaneDuncan602 — CHANGES_REQUESTED** [review]
Just the removal of the setAppManagerAddress function and adding the propose event.

**Review by ShaneDuncan602 — APPROVED** [review]
Looks great!

**Comment by ShaneDuncan602** [comment]
merged to external

**Pull request closed without merging**
