### PR TITLE
Audit 3 - Make handlers ownable by their controlling asset

### PR DESCRIPTION
**Pull request by ShaneDuncan602**

### CODE REVIEW

**Review by TJ-Everett — COMMENTED** [review]
Since this will be after my zero address changes we should check that the _assetAddress is not zero.

**Comment by ShaneDuncan602** [comment]
I agree. Good call.

**Review by TJ-Everett — APPROVED** [review]
Approved

**Review by TJ-Everett — APPROVED** [review]
Approved App Handler Changes

**Comment by jjbailey-io** [comment]
#25

**Comment by ShaneDuncan602** [comment]
merged with external

**Pull request closed without merging**
