### PR TITLE
Se 169 code quality duplicate code and typos

### PR DESCRIPTION
**Pull request by oscarsernarosero**
Half of the ticket tasks had already been taken care of in other tickets. Some condierations:

- `removelevel` function --which original task was to make it camel case-- was removed since this function is never used. Moreover setLevel(0) would do exactly the same.
- The Rule enum was also removed because it is a fossil from when the rules were passed through arrays during the last ice age.
- I took the liberty of removing `defaultFee` from the Fees.sol file since it was never used even though it was not specified in the ticket. I did notice some opportunities for improvement here, but that's more for a design meeting.
- I looked for more stuff to improve, but didn't really find anything, although Im not that good at finding stuff this way, so I kinda limited myself to the scope of the ticket.

### CODE REVIEW

**Review by ShaneDuncan602 — CHANGES_REQUESTED** [review]
appAdminstratorOrOwnerOnly is still misspelled. I guess the IToken was already addressed so that all looks good.

**Comment by oscarsernarosero** [comment]
> appAdminstratorOrOwnerOnly is still misspelled. I guess the IToken was already addressed so that all looks good.

oops! I guess I mis-misspelled when I was looking for it. Thank you for that Shane.

**Review by ShaneDuncan602 — APPROVED** [review]
Looks good.

**Review by TJ-Everett — APPROVED** [review]
Approved. Looks Great Oscar

**Pull request merged**
