### PR TITLE
Add conditional in proposeSuperAdmin

### PR DESCRIPTION
**Pull request by TJ-Everett**
- prevent current super admin from proposing self

### CODE REVIEW

**Review by ShaneDuncan602 — CHANGES_REQUESTED** [review]
We need to add the new error to ErrorSelctorss.md

**Comment by Palmerg4** [comment]
Looks good! Seconded what Shane mentioned. Will approve once the selector is added to docs.

**Review by Palmerg4 — APPROVED** [review]
Looks good!

**Review by ShaneDuncan602 — APPROVED** [review]
Perfect!

**Pull request merged**
