### PR TITLE
Audit 13 - Reverted the addTransferCounterRule event back where it wa…

### PR DESCRIPTION
**Pull request by ShaneDuncan602**
…s pre-audit

### CODE REVIEW

**Comment by TJ-Everett** [comment]
Did we want to also move the event on the diamond cut in this as well? Or are we okay with the event inside the loop for that one?

**Comment by ShaneDuncan602** [comment]
> 

Yep, you're right. I had to read Elvis's reply a few more times to understand it. Good catch.

**Review by TJ-Everett — APPROVED** [review]
approved

**Review by oscarsernarosero — APPROVED** [review]
Im glad we reverted this change. The indexer can take care of this rule with a single event as it is rn.

**Comment by ShaneDuncan602** [comment]
merged to external

**Pull request closed without merging**
